feat: Simplify configuration of delay between retries
CodingAleCR/http_interceptor pull request #122
Opened 2023-03-14 19:02 UTC by jonasschaude

This PR adds the possibility to configure a delay between retries. Sometimes it is helpful to have a "cool down" phase between multiple requests. This could for example also differ between the first and the second retry attempt as shown in `example/lib/weather_app.dart`.

2023-03-29 18:37 UTC, jonasschaude commented
Any updates on this PR? Do I have to further adapt something or could this be integrated? 😉

2023-04-13 21:38 UTC, CodingAleCR commented
hi, @jonasschaude this is failing the CI for some reason, I'll check it out and get back to you, in case there's anything that needs fixing.

2023-05-25 14:47 UTC, CodingAleCR commented
I am confirming that the failed checks are because of the pipeline and not your code. I'll fix this and hopefully release soon.

2023-05-27 00:31 UTC, CodingAleCR requested changes
@jonasschaude this looks great. Could you please update the README to reflect the added features?

2023-06-20 20:11 UTC, jonasschaude commented
> Hi @jonasschaude are you able to update the README?

Hey @CodingAleCR thanks a lot for reviewing the PR. I managed in the meantime to update the `README` file. Would be happy if you could double check the changes once again and let me know if there is more that needs to be adapted. Thanks in advance.

2023-08-23 20:00 UTC, jonasschaude commented
@CodingAleCR do you have any update on this? ;)

2024-04-10 02:41 UTC, merged