Pool Manager: limit, pause and cancel requests
CodingAleCR/http_interceptor pull request #96
Opened 2021-10-28 09:45 UTC by vixez

This is a PR related to https://github.com/CodingAleCR/http_interceptor/issues/92

The goal is to limit the amount of simultaneous requests, and pause requests when a token is being updated.
It is also possible to cancel active requests.

`PoolManager` can handle both of these.
I have added an explanation to `README.md` and updated `CHANGELOG.md` as well.

### Pool Manager  
  
Using a `PoolManager` allows you to set the maximum amount of simultaneous requests, and pause  
requests during token updates.  
  
Create a `PoolManager` and assign it to an `InterceptedClient`:  
  
```dart 
final PoolManager poolManager = PoolManager(    
  maxActiveConnections: 8, 
);  
  
InterceptedClient.build(    
  poolManager: poolManager, 
);  
```   
In the above example only 8 requests can be active at once. By default this is 32.  

#### Skip the pool

It is possible to skip a pool that is active, on hold, or blocked by a token update.
This can be useful to, for example, update a token in a `RetryPolicy` while the pool is on hold.
If the `InterceptedClient.kSkipPoolHeader` header is found in the request the pool will be skipped, so the request is executed immediately.

To your headers, add for example:
```dart
headers[InterceptedClient.kSkipPoolHeader] = 'true';
```

The value of the header does not matter and the `InterceptedClient.kSkipPoolHeader` is filtered out of the request before being sent to the server.
  
#### Refreshing a token  
  
If you use a `RetryPolicy` you can use the `PoolManager` to put new requests on hold until  
the `RetryPolicy` has completed. Use `requestUpdateToken` to let the `PoolManager` know you want to  
update the token and put new requests on hold. Once you have updated the token,  
use `releaseUpdateToken` to resume requests.  
  
Be sure to add logic (through an interceptor) to update queued requests with the new token you got  
in the `RetryPolicy`.  
  
`poolManager` in the example should be a reference to where you stored the `PoolManager` you  
assigned to `InterceptedClient`.  
  
```dart  
class TokenRetryPolicy extends RetryPolicy {  
  @override Future<bool> shouldAttemptRetryOnResponse(ResponseData response) async { 
    if (response.statusCode == 401) { 
     // Need to get a new token 
     await poolManager.requestUpdateToken();  
     
     /*  --- YOUR TOKEN REFRESH LOGIC --- */  
     
     poolManager.releaseUpdateToken(); return true; } 
     return false; 
   }
 }  
```

#### Cancel active requests
You can cancel all requests that have not yet returned a response. They will return with `RequestCancelledException`.
This is done through the `PoolManager` with `cancelRequests` (optionally releasing token updates with the `forceReleaseUpdateToken`) parameter.

2021-11-14 03:20 UTC, CodingAleCR commented
Hey, this looks amazing, I will continue testing it out with the new 2.0.0 APIs, thank you for all the hard work you have put into this!

2021-11-15 12:28 UTC, vixez commented
You're welcome. Let me know if there is anything I need to change/can do.

2022-01-10 13:41 UTC, vixez commented
I have updated this to work with the 2.0.0 beta.

2022-01-21 14:27 UTC, fnicastri commented
Any update on this @CodingAleCR ? Looking forward to use this on my app(almost ready to be released) app!

Thanks for this awesome lib!

2022-01-26 18:23 UTC, CodingAleCR commented
Not just yet, I have been trying to avoid adding significant new features while beta testing the new API that adds support for different types of requests and responses. 

However, I do appreciate the patience and the hard work been put in by the different contributors and interested supporters 🎉

2022-01-27 09:10 UTC, fnicastri commented
@CodingAleCR @vixez  Thanks!

2022-02-07 11:02 UTC, vixez commented
Added the ability to cancel all requests that have not yet returned a response

2022-03-21 12:07 UTC, vixez commented
That could be an option as well, yes 🤔

2022-05-13 03:01 UTC, LucPham commented
waiting!!

2022-08-01 18:22 UTC, fnicastri commented
🤷‍♂️

2022-08-10 18:33 UTC, CodingAleCR requested changes
I've explored other options but none that I like as alternatives, this has the most potential and stability. Would you be willing to update the PR with the latest changes?

2022-08-10 18:33 UTC, CodingAleCR commented on lib/http_interceptor.dart
> -export 'package:http/http.dart';
I think it's best if we expose `http` package along with this package so we can avoid having to install manually `http` when using `http_interceptor`.

2023-01-27 15:24 UTC, shinayser commented
Is this feature still be implemented or its abbandoned?

2023-01-31 15:40 UTC, CodingAleCR commented
I asked for a couple of updates. When done it should be good to go

2023-03-09 10:19 UTC, vixez commented
@shinayser I have rewritten major parts of our API code for the app, making this no longer needed.

2023-05-21 18:48 UTC, closed without merging